### ISSUE TITLE
Makefile doesn't build docs

### ISSUE THREAD

**Issue by ericholscher** [commandodev/stargate#1]
Your Makefile references a sphinx-build executable that doesn't exist (../bin/sphinx-build). If you take the bin part off it should just work with the globally installed sphinx.

**Comment by commandodev** [comment]
Right you are, it's referring to the zc.buildout environment which shouldn't be needed now. I'll try and get round to updating it in the next day or two.

**Comment by commandodev** [comment]
Done  - forgot to close!
