### ISSUE TITLE
Installing using easy_install -- README.gst  MISSING

### ISSUE THREAD

**Issue by glesperance** [commandodev/stargate#2]
greenvelvet:~ glesperance$ easy_install stargate
Searching for stargate
Reading http://pypi.python.org/simple/stargate/
Reading http://github.com/boothead/stargate
Best match: stargate 0.2
Downloading http://pypi.python.org/packages/source/s/stargate/stargate-0.2.tar.gz#md5=28018009b7aec1449a2eaaf7d2e35a3e
Processing stargate-0.2.tar.gz
Running stargate-0.2/setup.py -q bdist_egg --dist-dir /var/folders/Zo/ZolePPEwF4q8mQxG+uPClU+++TI/-Tmp-/easy_install-zo9ohq/stargate-0.2/egg-dist-tmp-8OjCw3
error: README.rst: No such file or directory

---

I managed to manually install the package by doing 
     easy_install -eb . stargate 

and editing setup.py and setting 

```
long_description = ""
```

then 

```
easy_install . 
```

while in the directory...

In any case, it seems that the package is missing a file that blocks the normal installation flow.

**Comment by glesperance** [comment]
After further investigation, the package on http://pypi.python.org/ differs from the github one.

**Comment by commandodev** [comment]
Yeah that's a weird one, I'll sort it out a little later today. Thanks for the catch!

**Comment by commandodev** [comment]
OK, This is fixed. I've bumped the version too as I took the opportunity to fix up some other stuff

Cheers,
Ben
